name: Deploy to GitHub Pages
on: push
jobs: 
  deploy:
    name: Deploy to Github-Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
      run: npm install

    - name: Deploy
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
      run: npm run deploy