name: "Build"
on: push
jobs: 
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
      run: npm install
      
    - name: Build
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
      run: npm run build